In [33]:
import pandas as pd

In [34]:
'''Must create backups manually at this time!!
Add _BACKUP to the name of the .txt file in Updates and move it to 
 Backups folder before running this script!'''

'Must create backups manually at this time!!\nAdd _BACKUP to the name of the .txt file in Updates and move it to \n Backups folder before running this script!'

In [35]:
df = pd.read_csv('./Data/CAINC5N_NC_2001_2017.csv')
df.head()

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,2001,2002,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,"""37000""",North Carolina,5.0,CAINC5N,10.0,...,Personal income (thousands of dollars),Thousands of dollars,228431654,231805733,...,350372649,337787031,340764297,354294372,379031187,375057001,397410713,419888909,433766368,454306904
1,"""37000""",North Carolina,5.0,CAINC5N,20.0,...,Population (persons) 2/,Number of persons,8210122,8326201,...,9309449,9449566,9574247,9662940,9755299,9849812,9941160,10041769,10156689,10273419
2,"""37000""",North Carolina,5.0,CAINC5N,30.0,...,Per capita personal income (dollars),Dollars,27823,27841,...,37636,35746,35592,36665,38854,38078,39976,41814,42707,44222
3,"""37000""",North Carolina,5.0,CAINC5N,35.0,...,Earnings by place of work,Thousands of dollars,174113335,176206894,...,257505459,243168101,243762027,247464422,267072169,266760383,280027813,294005281,303794979,318753696
4,"""37000""",North Carolina,5.0,CAINC5N,36.0,...,Less: Contributions for government social ins...,Thousands of dollars,20100040,20369137,...,28278511,27492664,27812781,25926513,26956299,31307775,32873914,34556456,35607243,36977394

In [36]:
df.to_csv('./Updates/STG_BEA_CAINC5N_NC_2001_2017.txt', sep = '\t')