In [ ]:
## Written and published by Nathan Young, Junior Data Analyst for NC Data Dashboard, October 2019 ##

In [1]:
# Imports  
import pandas as pd

In [2]:
# Create backups
df_backup = pd.read_csv('./Updates/STG_FRED_Unemployment_Rate_by_County_Percent.txt')
df_backup.to_csv('./Backups/STG_FRED_Unemployment_Rate_by_County_Percent_BACKUP.txt')

In [3]:
# Getting and reading new data 
df = pd.read_excel("https://geofred.stlouisfed.org/api/download.php?theme=pubugn&colorCount=5&reverseColors=false&intervalMethod=fractile&displayStateOutline=true&lng=-89.96&lat=40.01&zoom=4&showLabels=true&showValues=true&regionType=county&seriesTypeId=1224&attributes=Not+Seasonally+Adjusted%2C+Monthly%2C+Percent&aggregationFrequency=Annual&aggregationType=Average&transformation=lin&date=2018-01-01&type=xls&startDate=1976-01-01&endDate=2018-01-01&mapWidth=999&mapHeight=1249&hideLegend=false", skiprows=1)
df.head(5)

,Series ID,Region Name,Region Code,1976,1977,1978,1979,1980,1981,1982,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,SCABBE1URN,"Abbeville County, SC",45001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.175000,13.591667,12.450000,10.633333,9.500000,7.725000,6.891667,5.500000,4.583333,3.983333
1,LAACAD0URN,"Acadia Parish, LA",22001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.458333,7.258333,6.683333,5.991667,5.950000,5.741667,6.850000,7.366667,5.908333,5.358333
2,VAACCO1URN,"Accomack County, VA",51001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.508333,7.916667,8.408333,7.883333,7.233333,6.700000,5.458333,4.950000,4.525000,3.816667
3,IDADAC1URN,"Ada County, ID",16001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.908333,8.308333,7.333333,6.183333,5.208333,4.150000,3.675000,3.300000,2.833333,2.475000
4,KYADURN,"Adair County, KY",21001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.750000,12.441667,11.783333,9.500000,10.141667,8.616667,7.175000,6.658333,6.066667,5.058333

In [4]:
# Filter data to display only North Carolina
filter1 = df['Region Name'].str.contains(', NC')
df_nc = df[filter1]
df_nc.head()

,Series ID,Region Name,Region Code,1976,1977,1978,1979,1980,1981,1982,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
24,NCALAM1URN,"Alamance County, NC",37001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.675000,10.866667,9.658333,8.533333,7.250000,5.683333,5.341667,4.750000,4.225000,3.658333
35,NCALEX3URN,"Alexander County, NC",37003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.866667,13.041667,11.275000,9.575000,7.766667,5.633333,4.925000,4.241667,3.625000,3.150000
44,NCALLE5URN,"Alleghany County, NC",37005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.891667,12.016667,12.258333,10.450000,8.783333,6.866667,6.141667,5.491667,5.033333,4.508333
70,NCANSO7URN,"Anson County, NC",37007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.791667,14.125000,12.283333,10.908333,9.466667,7.083333,6.508333,5.800000,5.116667,4.475000
89,NCASHE9URN,"Ashe County, NC",37009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.000000,11.833333,10.958333,10.441667,9.191667,6.875000,6.025000,4.808333,4.066667,3.600000

In [5]:
# Save file to tab delimited txt for upload to SSMS
df_nc.to_csv('./Updates/STG_FRED_Unemployment_Rate_by_County_Percent.txt', sep = '\t')