In [18]:
## Written and published by Nathan Young, Junior Data Analyst for NC Data Dashboard, December 2019 ##

In [19]:
# Imports
import pandas as pd
import requests
from io import BytesIO, StringIO
from zipfile import ZipFile

In [20]:
# Create Backups
df_backup = pd.read_csv('./Updates/STG_BEA_CAINC5N_NC.txt', encoding = 'ISO-8859-1', sep='\t')
df_backup.to_csv('./Backups/STG_BEA_CAINC5N_NC_BACKUP.txt')

In [21]:
# Load BEA CAINC5N_NC data
response = requests.get('https://apps.bea.gov/regional/zip/CAINC5N.zip')
zip_file = ZipFile(BytesIO(response.content))
files = zip_file.namelist()
with zip_file.open(files[34]) as csvfile:
    df = pd.read_csv(csvfile, encoding='ISO-8859-1', sep=",")

In [22]:
# Check for non-data fields
df.tail(10)

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,2001,2002,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
13225,"""37199""","Yancey, NC",5.0,CAINC5N,2000.0,...,Government and government enterprises,Thousands of dollars,31811,32905,...,42039,43069,42119,41528,40990,40595,42823,50157,51335,51005
13226,"""37199""","Yancey, NC",5.0,CAINC5N,2001.0,...,Federal civilian,Thousands of dollars,2992,3157,...,3041,3715,3545,3446,2180,2227,3371,3270,3197,3318
13227,"""37199""","Yancey, NC",5.0,CAINC5N,2002.0,...,Military,Thousands of dollars,652,881,...,1768,1687,1633,1480,1389,1287,1220,1261,1221,1308
13228,"""37199""","Yancey, NC",5.0,CAINC5N,2010.0,...,State and local,Thousands of dollars,28167,28867,...,37230,37667,36941,36602,37421,37081,38232,45626,46917,46379
13229,"""37199""","Yancey, NC",5.0,CAINC5N,2011.0,...,State government,Thousands of dollars,5028,5552,...,6036,5825,5599,5728,5874,5297,5224,5508,5512,5843
13230,"""37199""","Yancey, NC",5.0,CAINC5N,2012.0,...,Local government,Thousands of dollars,23139,23315,...,31194,31842,31342,30874,31547,31784,33008,40118,41405,40536
13231,Note: See the included footnote file.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13232,CAINC5N: Personal Income by Major Component an...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13233,"Last updated: November 14, 2019-- new statisti...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13234,Source: U.S. Department of Commerce / Bureau o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# Remove non-data fields
df_clean = df[:-4]
df_clean.tail(5)

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,2001,2002,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
13226,"""37199""","Yancey, NC",5.0,CAINC5N,2001.0,...,Federal civilian,Thousands of dollars,2992,3157,...,3041,3715,3545,3446,2180,2227,3371,3270,3197,3318
13227,"""37199""","Yancey, NC",5.0,CAINC5N,2002.0,...,Military,Thousands of dollars,652,881,...,1768,1687,1633,1480,1389,1287,1220,1261,1221,1308
13228,"""37199""","Yancey, NC",5.0,CAINC5N,2010.0,...,State and local,Thousands of dollars,28167,28867,...,37230,37667,36941,36602,37421,37081,38232,45626,46917,46379
13229,"""37199""","Yancey, NC",5.0,CAINC5N,2011.0,...,State government,Thousands of dollars,5028,5552,...,6036,5825,5599,5728,5874,5297,5224,5508,5512,5843
13230,"""37199""","Yancey, NC",5.0,CAINC5N,2012.0,...,Local government,Thousands of dollars,23139,23315,...,31194,31842,31342,30874,31547,31784,33008,40118,41405,40536

In [24]:
# Set GeoFIPS as Index
df_clean.set_index(df_clean['GeoFIPS'], inplace = True)
df_clean.head(2)

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,2001,2002,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
GeoFIPS,,,,,,,,,,,,,,,,,,,,,
"""37000""","""37000""",North Carolina,5.0,CAINC5N,10.0,...,Personal income (thousands of dollars),Thousands of dollars,228879962,232267281,...,338315713,341627602,355052267,379925288,376023857,397995923,419891523,433195584,453769026,478861557
"""37000""","""37000""",North Carolina,5.0,CAINC5N,20.0,...,Population (persons) 2/,Number of persons,8210122,8326201,...,9449566,9574293,9656754,9749123,9843599,9933944,10033079,10156679,10270800,10383620

In [25]:
# Drop GeoFIPS column
df_clean.drop('GeoFIPS', axis = 1, inplace = True)
df_clean.head(2)

,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,2001,2002,2003,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
GeoFIPS,,,,,,,,,,,,,,,,,,,,,
"""37000""",North Carolina,5.0,CAINC5N,10.0,...,Personal income (thousands of dollars),Thousands of dollars,228879962,232267281,241625829,...,338315713,341627602,355052267,379925288,376023857,397995923,419891523,433195584,453769026,478861557
"""37000""",North Carolina,5.0,CAINC5N,20.0,...,Population (persons) 2/,Number of persons,8210122,8326201,8422501,...,9449566,9574293,9656754,9749123,9843599,9933944,10033079,10156679,10270800,10383620

In [26]:
# Save as tab-delimited txt file for export to SSMS
df_clean.to_csv('./Updates/STG_BEA_CAINC5N_NC.txt', sep = '\t')