In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('https://injuryfreenc.shinyapps.io/OpioidActionPlan/_w_31be441b/session/a4b21297919ad5ae607a8e350984e368/download/download_all_data?w=31be441b')

In [7]:
df

,place,year,quarter,pop,unint_opioid_deaths_n,opioid,multiple_episodes_n,pills_n,patients_90mme_pct,rxdays_opioidandbenzo_pct,fent_heroin_death_pct,acute_hep_c_n,ems_naloxone_n,comm_naloxone_n,bupronorphine_scripts_n,opioid_dx_un,cpss_n,region_type
0,Alamance,1999,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,county
1,Alexander,1999,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,county
2,Alleghany,1999,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,county
3,Anson,1999,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,county
4,Ashe,1999,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,county
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9298,UNKNOWN,2017,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149.0,NaN,NaN,NaN,NaN,county
9299,UNKNOWN,2018,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.0,NaN,NaN,NaN,NaN,county
9300,UNKNOWN,2018,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,151.0,NaN,NaN,NaN,NaN,county
9301,UNKNOWN,2018,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,county
9302,UNKNOWN,2018,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,county